GroupP/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :events
    resources :memos
  end

  

  root 'home#index'

end

GroupP/app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name, :date, :description
  has_many :join_tables
  has_many :users, through: :join_tables
  belongs_to :user
end

GroupP/app/models/join_table.rb
class JoinTable < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

GroupP/app/models/memo.rb
class Memo < ActiveRecord::Base
  validates_presence_of :name, :content
  belongs_to :user
end

GroupP/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  has_many :join_tables
  has_many :memos
end

GroupP/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

GroupP/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @user = User.find current_user
    @events = @user.events
  end
  def new
    @users = User.all
    @event = Event.new
  end
  def create
    @user = User.find current_user
    @event = @user.events.new(event_params)
    if @event.save
      flash[:notice] = 'Event was successfully added.'
      redirect_to user_events_path(current_user)
    else
      flash[:error] = "Event was NOT added."
      render :new
    end
  end
  
  def show
    set_event
    @users = User.all
  end

  def edit
    set_event
    @users = User.all
  end

  def update
    @user= User.find current_user
    set_event
    @user.events.update_attributes event_params
    if @event.update_attributes event_params
      flash[:notice] = 'Event was successfully added.'
      redirect_to user_event_path(current_user.id, @event)
    else
      flash[:error] = "Event was NOT added."
      render :edit
    end
  end

  def destroy
    set_event
    @event.destroy
    redirect_to root_path
  end

private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(
      :name,
      :description,
      :date,
      :user_id,
      user_ids: [],
      event_ids: []
      )
  end
end

GroupP/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
  def events
    @events = Event.this_month 
  end
end

GroupP/app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    @user = User.find current_user
    @memos = @user.memos
  end

  def new
    @users = User.all
    @memo = Memo.new
  end

  def create
    @user = User.find current_user
    @memo = @user.memos.new(memo_params)
    if @memo.save
    flash[:notice] = 'Memo was successfully added.'
    redirect_to root_path
    else
      flash[:error] = "Memo was NOT added."
      render :new 
    end
  end

  def show
    set_memo
    @users = User.all
  end
  def edit
    set_memo
    @users = User.all
  end
  def update
    @user = User.find current_user
    set_memo
    @user.memos.update_attributes memo_params
    if @user.memos.update_attributes memo_params
      flash[:notice] = 'Memo was successfully added.'
      redirect_to user_memo_path(@user, @memo)
    else
      flash[:error] = "Memo was NOT added."
      render :edit
    end
  end
  def destroy
    set_memo
    @memo.destroy
    redirect_to root_path
  end
private
  def set_memo
    @memo = Memo.find(params[:id])
  end 

  def memo_params
    params.require(:memo).permit(
      :name,
      :content,
      :user_id
      )
  end
end

GroupP/app/helpers/application_helper.rb
module ApplicationHelper
end

GroupP/app/helpers/events_helper.rb
module EventsHelper
end

GroupP/app/helpers/home_helper.rb
module HomeHelper
end

GroupP/app/helpers/memos_helper.rb
module MemosHelper
end

GroupP/app/views/events/_form.html.haml
- if @event.errors.any?
  - @event.errors.full_messages.each do |message|
    %span.glyphicon.glyphicon-exclamation-sign
    %span= message
    %br/
= form_for [current_user, @event] do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :description
  = f.text_area :description
  %br
  = f.label :date
  = f.date_field :date
  %br
  %p
    Who will be attending this event?
  - @users.each do |c|
    = check_box_tag 'event[user_ids][]', c.id, @event.users.include?(c)
    = c.email
    %br
  %br
  = f.submit

GroupP/app/views/events/index.html.haml
%h1 Events
- @events.each do |event|
  .btn.btn-default
    = link_to user_event_path(current_user, event) do
      = event.name
  %br
= link_to new_user_event_path(current_user.id), class: 'glyph' do
  %float.glyphicon.glyphicon-plus
  %float Event
%br

GroupP/app/views/events/new.html.haml
%h1 New Event
= render 'form'

GroupP/app/views/events/show.html.haml
%h1 Event
%h4
  Name: #{@event.name}
  %br
  Description: #{@event.description}
  %br
  Date: #{@event.date.strftime("%m/%d/%Y")}
  %br
  = link_to edit_user_event_path(current_user, @event) do
    %span.glyphicon.glyphicon-edit{class: 'glyph'}
  = link_to user_event_path(current_user, @event), method: :delete do
    %span.glyphicon.glyphicon-trash{class: 'glyph'}

GroupP/app/views/home/index.html.haml
%div
  %h1 Home

-if user_signed_in?
  = calendar_for(@events) do |t|
    = t.head('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun')
    = t.day do |day, events|
      = day.day
      - events.each do |event|
        = h(event.name)
        

GroupP/app/views/layouts/_navbar.html.haml
%ul.nav.navbar-nav
  %p.navbar-text.pull-right
    - if user_signed_in?
      Logged in as
      = succeed "." do
        %strong= current_user.email
      = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
      |
      \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
    - else
      = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
      |
      \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}
      hi

GroupP/app/views/layouts/_sidebar.html.haml
= render 'sidebar'

GroupP/app/views/layouts/_todo.html.haml
%h3 To Do List
%ul
  %li
    thing1
  %li
    thing2

GroupP/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %title PDA
          %link{:href => "css/bootstrap.min.css", :rel => "stylesheet"}
            = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
            = javascript_include_tag 'application', 'data-turbolinks-track' => true
            = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top{:role => "login"}
      %div.container
        = link_to root_path, class: 'navbar-link btn btn-default navbar-btn' do
          %span.glyphicon.glyphicon-home{class: "glyph"}
        - if user_signed_in?
          = link_to 'Events', user_events_path(current_user.id), :class => 'navbar-link btn btn-default navbar-btn'
          = link_to 'Memos', user_memos_path(current_user.id), :class => 'navbar-link btn btn-default navbar-btn'
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", edit_user_registration_path
                %li= link_to "Settings", '#'
                %li.divider
                %li
                  = link_to "Logout", destroy_user_session_path, :method => :delete
          - else
            = link_to "Sign up", new_user_registration_path, :class => 'navbar-link btn btn-default navbar-btn'
            = link_to "Login", new_user_session_path, :class => 'navbar-link btn btn-default navbar-btn'
    %div.container-sidebar
      %div.row
        %div.col-md-3.sidebar-style
          = render 'layouts/sidebar'
      %div.container
        %div.row
          %div.col-md-3
            %div.col-md-9
              %div.body-content-style
                - if flash[:notice]
                  %h5#notice= flash[:notice]
                - if flash[:error]
                  %h5#error= flash[:error]
                = yield

GroupP/app/views/memos/_form.html.haml
- if @memo.errors.any?
  - @memo.errors.full_messages.each do |message|
    %span.glyphicon.glyphicon-exclamation-sign
    %span= message
    %br/
= form_for [current_user, @memo] do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :content
  = f.text_area :content
  %br
  = f.submit

GroupP/app/views/memos/edit.html.haml
= render 'form'

GroupP/app/views/memos/index.html.haml
%h1 Memos
- @memos.each do |memo|
  .btn.btn-default
    = link_to user_memo_path(current_user, memo) do
      = memo.name
  %br
= link_to new_user_memo_path(current_user.id), class: 'glyph' do
  %float.glyphicon.glyphicon-plus
  %float Memo

GroupP/app/views/memos/new.html.haml
%h1 New Memo
= render 'form'

GroupP/app/views/memos/show.html.haml
%h1 Memo
%h4
  Name: #{@memo.name}
  %br
  Description: #{@memo.content}
  %br
  = link_to edit_user_memo_path(current_user, @memo) do
    %span.glyphicon.glyphicon-edit{class: 'glyph'}
  = link_to user_memo_path(current_user, @memo), method: :delete do
    %span.glyphicon.glyphicon-trash{class: 'glyph'}